service: loop-aws-node-demo-app

custom:
    stage: ${opt:stage, 'offline'}

    serverless-offline:
        httpPort: 4003
        noPrependStageInUrl: true

    prune:
        automatic: true
        number: ${file(./stages/${self:custom.stage}.yml):prune}
        verbose: true

useDotenv: true

provider:
    name: aws
    runtime: nodejs16.x
    region: us-east-2
    environment: ${file(./stages/${self:custom.stage}.yml):environment}
    timeout: 400
    logRetentionInDays: 30
    logs:
        httpApi: true
    vpc:
        securityGroupIds:
            - ${file(./stages/${self:custom.stage}.yml):securityGroupId}
        subnetIds:
            - ${file(./stages/${self:custom.stage}.yml):subnetId1}
            - ${file(./stages/${self:custom.stage}.yml):subnetId2}
            - ${file(./stages/${self:custom.stage}.yml):subnetId3}

plugins:
    - serverless-offline

functions:
    webhook-handler:
        handler: src/handler.incoming
        events:
            - http:
                  path: loop/webhook
                  method: post
